// hello world actions
export const HELLO_WORLD = 'HELLO_WORLD';
export const HELLO_WORLD_END = 'HELLO_WORLD_END';
// auth actions
export const DO_LOGIN = 'DO_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const DO_REGISTER = 'DO_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
// user actions
export const CLOSE_SESSION = 'CLOSE_SESSION';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_ERROR';
// class actions
export const GET_ALL_CLASSROOM = 'GET_ALL_CLASSROOM';
export const GET_ALL_CLASSROOM_SUCCESS = 'GET_ALL_CLASSROOM_SUCCESS';
export const GET_ALL_CLASSROOM_ERROR = 'GET_ALL_CLASSROOM_ERROR';
export const CREATE_CLASS = 'CREATE_CLASS';
export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const CREATE_ERROR = 'CREATE_ERROR';
export const GET_ONE_CLASSROOM = 'GET_ONE_CLASSROOM';
export const GET_ONE_CLASSROOM_SUCCESS = 'GET_ONE_CLASSROOM_SUCCESS';
export const GET_ONE_CLASSROOM_ERROR = 'GET_ONE_CLASSROOM_ERROR';
