// auth actions
export const DO_LOGIN = 'DO_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const DO_OAUTH_LOGIN = 'DO_OAUTH_LOGIN';
export const DO_REGISTER = 'DO_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const DO_LOGOUT = 'DO_LOGOUT';

// user actions
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_ERROR';
export const GET_ONE_PROFILE = 'GET_ONE_PROFILE';
export const GET_ONE_PROFILE_SUCCESS = 'GET_ONE_PROFILE_SUCCESS';
export const GET_ONE_PROFILE_ERROR = 'GET_ONE_PROFILE_ERROR';
// classroom actions
export const GET_ALL_CLASSROOM = 'GET_ALL_CLASSROOM';
export const GET_ALL_CLASSROOM_SUCCESS = 'GET_ALL_CLASSROOM_SUCCESS';
export const GET_ALL_CLASSROOM_ERROR = 'GET_ALL_CLASSROOM_ERROR';
export const CREATE_CLASSROOM = 'CREATE_CLASSROOM';
export const CREATE_CLASSROOM_SUCCESS = 'CREATE_CLASSROOM_SUCCESS';
export const CREATE_CLASSROOM_ERROR = 'CREATE_CLASSROOM_ERROR';
export const GET_ONE_CLASSROOM = 'GET_ONE_CLASSROOM';
export const GET_ONE_CLASSROOM_SUCCESS = 'GET_ONE_CLASSROOM_SUCCESS';
export const GET_ONE_CLASSROOM_ERROR = 'GET_ONE_CLASSROOM_ERROR';
export const GET_USER_TEACHED_CLASSROOMS = 'GET_USER_TEACHED_CLASSROOMS';
export const GET_USER_TEACHED_CLASSROOMS_SUCCESS = 'GET_USER_TEACHED_CLASSROOMS_SUCCESS';
export const GET_USER_TEACHED_CLASSROOMS_ERROR = 'GET_USER_TEACHED_CLASSROOMS_ERROR';
export const GET_USER_FOLLOWED_CLASSROOMS = 'GET_USER_FOLLOWED_CLASSROOMS';
export const GET_USER_FOLLOWED_CLASSROOMS_SUCCESS = 'GET_USER_FOLLOWED_CLASSROOMS_SUCCESS';
export const GET_USER_FOLLOWED_CLASSROOMS_ERROR = 'GET_USER_FOLLOWED_CLASSROOMS_ERROR';
export const UPDATE_CLASSROOM = 'UPDATE_CLASSROOM';
export const UPDATE_CLASSROOM_SUCCESS = 'UPDATE_CLASSROOM_SUCCESS';
export const UPDATE_CLASSROOM_ERROR = 'UPDATE_CLASSROOM_ERROR';
export const SEARCH_CLASSROOMS = 'SEARCH_CLASSROOMS';
// notifications actions
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
// observable actions
export const ADD_OBSERVABLE = 'ADD_OBSERVABLE';
export const REMOVE_OBSERVABLE = 'REMOVE_OBSERVABLE';
